### ISSUE TITLE
less.render not support  syncImport:true   rendering @import

### ISSUE THREAD

**Issue by huanshiwushuang** [FranckFreiburger/vue3-sfc-loader#101] opened 2021-08-15 13:17 UTC
**Describe the bug**

less.render() does not support synchronous rendering @import.
The syncImport attribute is invalid. If there is an @import string and syncImport: true, the callback function will never be called

The code from @vue/compiler-sfc/dist/compiler-sfc.cjs.js
```
nodeLess.render(getSource(source, options.filename, options.additionalData), Object.assign(Object.assign({}, options), { syncImport: true }), (err, output) => {
        error = err;
        result = output;
    });
```

**To Reproduce**

**Expected behavior**

**Versions**
 - Browser (name & version): chrome  92.0.4515.131
 - vue3-sfc-loader: https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.8.4/dist/vue2-sfc-loader.esm.js

**Additional context**

**Comment by FranckFreiburger** [comment] 2024-01-23 17:04
Duplicate of #54

**Closed by FranckFreiburger** 2024-01-23 17:04 UTC
Labels: bug, unconfirmed
