### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by bug4j** [FranckFreiburger/vue3-sfc-loader#121] opened 2021-11-16 13:31 UTC
hi，
is there a way to generate or link the script that which was complied to a sourceMap file ? because it is impossible to debug from what i see.

**Comment by sakana280** [comment] 2022-09-26 11:16
You can sprinkle `debugger` statements throughout your SFC code. Not pretty but can help with the occasional specific bug.

**Comment by FranckFreiburger** [comment] 2024-01-07 18:27
duplicate of #123

**Closed by FranckFreiburger** 2024-01-07 18:27 UTC
Labels: bug, unconfirmed
