### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by jjjrmy** [FranckFreiburger/vue3-sfc-loader#132] opened 2022-05-20 21:27 UTC
```
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/user/Sites/my-new-site/node_modules/vue3-sfc-loader/dist/vue3-sfc-loader.js:9:218)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.741 (/Users/user/Sites/my-new-site/public/js/ssr.js:1:18216)
    at r (/Users/user/Sites/my-new-site/public/js/ssr.js:1:56381)
    at /Users/user/Sites/my-new-site/public/js/ssr.js:1:58711

Node.js v17.3.0
```

Trying to run this in NodeJS for SSR support on my app and getting this error.

**Comment by dbdxwb** [comment] 2023-04-14 00:45
Has this bug not been resolved yet ?

**Comment by FranckFreiburger** [comment] 2024-01-06 22:38
duplicate of #162

**Closed by FranckFreiburger** 2024-01-06 22:38 UTC
Labels: bug, unconfirmed
